### DISCUSSION TITLE
Leader Key Module

### DISCUSSION THREAD

**Discussion by nol00p** [KinesisCorporation/Adv360-Pro-ZMK#686] [Q&A] [answered]
I'd like to enable the leader key functionanlity from: https://github.com/urob/zmk-leader-key
I quite like this function on a QMK setup. 

problem is I can't get it to work, I have the very compiling issue documenent, but can't use the alternative repo described. 

any help welcome on that one :)

**Comment by KinesisCorporation** [comment]
@ReFil Is this supported on 360 Pro?

**Reply by ReFil** [reply]
Looking at the documentation for that module it doesn't seem like it's compatible out of the box but we may be able to fix the issue. @nol00p please can you make your repository public and share the link so I can look into the exact build failure?

**Reply by nol00p** [reply]
Hey, thanks for looking into it. let me create a repo for you, I am doing everything locally.

**Reply by nol00p** [reply]
here you go: https://github.com/nol00p/adv360

Please let me know if you need anything else ! thanks again.

**Reply by nol00p** [reply]
Hello @ReFil , anything I can do to help on this?

**Reply by nol00p** [reply, marked as answer]
this can be closed, I manage to build the leader key into the kynresis repo. if anybody wants to do it, here is my west.yml. 

```
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
    - name: urob
      url-base: https://github.com/urob
  projects:
    - name: zmk
      remote: refil
      revision: adv360-z3.5-2
      import: app/west.yml
    - name: zmk-leader-key
      remote: urob
      revision: v0.1 # match ZMK base of the refil fork (Jan 2025, post-v0.1)
    - name: zmk-helpers
      remote: urob
      revision: v0.1 # same pinning rationale as zmk-leader-key
  self:
    path: config

```
